// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class TblPromotion
    {
        public int Id { get; set; }
        public string PromotionId { get; set; } = null!;
        public int PromoTypeId { get; set; }
        public int ValueTypeId { get; set; }
        public int DiscountValue { get; set; }
        public string Item { get; set; } = null!;
        public string StoreId { get; set; } = null!;
        public string? Description { get; set; }
        public DateOnly StartDate { get; set; }
        public DateOnly EndDate { get; set; }

        public virtual TblStore Store { get; set; } = null!;
    }
}