// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class TblStore
    {
        public TblStore()
        {
            TblPromotion = new HashSet<TblPromotion>();
        }

        public string Store { get; set; } = null!;
        public string StoreName { get; set; } = null!;

        public virtual ICollection<TblPromotion> TblPromotion { get; set; }
    }
}